SELECT
    O_ORDERKEY AS ORDER_ID,
    O_CUSTKEY AS CUSTOMER_ID,
    O_ORDERSTATUS AS ORDER_STATUS,
    O_TOTALPRICE AS TOTAL_PRICE,
    O_ORDERDATE AS ORDER_DATE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS